### ISSUE TITLE
Missing buttons in UI Elements page

### ISSUE THREAD

**Issue by wobsoriano** [wobsoriano/v-dashboard#4] opened 2020-10-03 03:29 UTC
As the title says, there are missing buttons in the page.

![Screen Shot 2020-10-03 at 11 29 11 AM](https://user-images.githubusercontent.com/13049130/94982255-aacaf780-056b-11eb-85c3-6f890188abfb.png)

**Comment by LandonLloyd** [comment] 2020-10-03 03:31
Assign Me!

**Comment by LandonLloyd** [comment] 2020-10-03 03:31
I may not be able to get to it tonight but I will get it to you as soon as possible.

**Comment by sebassu** [comment] 2020-10-03 04:52
Hello, I'd like to be assigned to this issue if possible.

**Comment by jovi09** [comment] 2020-10-03 11:52
Hello what shades should the buttons be?

I would like to work on this issue!

**Comment by wobsoriano** [comment] 2020-10-03 11:56
Expected output

![Screen Shot 2020-10-03 at 7 56 08 PM](https://user-images.githubusercontent.com/13049130/94990972-7d556c80-05b2-11eb-94da-02e22a7ddaf9.png)

**Comment by jovi09** [comment] 2020-10-03 12:05
Also can i use npm instead? or is yarn to be used strictly?

**Comment by wobsoriano** [comment] 2020-10-03 12:09
> Also can i use npm instead? or is yarn to be used strictly?

can use any

**Comment by geeks5551** [comment] 2020-10-03 12:52
can i be assigned above issue ? looking interesting to work on it ?

**Comment by SohamDave08** [comment] 2020-10-04 17:33
Hey, Can you assign me this issue? I'm interested to contribute

**Comment by swapnalshahil** [comment] 2020-10-05 03:23
I guess the issue is solved. I can see all buttons as you mentioned above @wobsoriano

**Comment by wobsoriano** [comment] 2020-10-05 03:27
> I guess the issue is solved. I can see all buttons as you mentioned above @wobsoriano

are you sure? can you send a screenshot? thanks

**Comment by swapnalshahil** [comment] 2020-10-05 03:29
<img width="960" alt="2020-10-05" src="https://user-images.githubusercontent.com/58564017/95037557-12f31800-06e9-11eb-9519-0b52b12147a7.png">

is this?

**Comment by wobsoriano** [comment] 2020-10-05 03:31
> <img alt="2020-10-05" width="960" src="https://user-images.githubusercontent.com/58564017/95037557-12f31800-06e9-11eb-9519-0b52b12147a7.png">
> 
> is this?

hmm weird, looks like it works locally but missing in production. I'll check this out, thanks!

**Comment by sebassu** [comment] 2020-10-07 01:43
This was indeed related to the purging process of Tailwind CSS. Some classes were not included on the production build, that were present locally while running `yarn dev`. Including those fixes the issue.

**Closed as completed** 2020-10-07 01:46 UTC
Labels: bug
